services:
  led_controller:
    build: .
    container_name: led_controller
    image: led_controller:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "6454:6454/udp"
    volumes:
      - led_data:/led_controller/data
      - led_data:/var/www/led_controller/images
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    container_name: led_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  led_data:
  redis_data:
