FROM led-controller-base:latest

COPY ./artnet.conf /led_controller/
COPY ./LedController.pm /led_controller/
COPY ./LedController/ /led_controller/LedController/
COPY ./artnetd.pl /led_controller/

USER www-data
CMD ["perl", "./artnetd.pl"]
