FROM led-controller-base:latest

# Copy Configuration frameworks
COPY ./artnet.conf /led_controller/
COPY ./000-default.conf /etc/apache2/sites-available/
COPY ./startup.pl /etc/apache2/perl/

# Copy Application Libraries/Modules
COPY ./LedController.pm /led_controller/
COPY ./LedController/ /led_controller/LedController/

# Copy Frontend Web Assets
COPY ./index.epl /var/www/led_controller/
COPY ./upload.js /var/www/led_controller/
COPY ./bootstrap.min.css /var/www/led_controller/
COPY ./bootstrap.min.css.map /var/www/led_controller/

# Enable necessary Apache modules
RUN a2enmod headers

# Ensure running runtime directories remain completely accessible to www-data
RUN chown -R www-data:www-data /led_controller/data && \
	chown -R www-data:www-data /var/www/led_controller/images

# Redirect apache error and access logs to stdout and stderr tubes
RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
	ln -sf /proc/self/fd/2 /var/log/apache2/error.log

CMD ["apachectl", "-D", "FOREGROUND"]
